config/routes.rb
FrontEnd::Application.routes.draw do
  resources :lessons do
    resources :questions 
  end
  resources :users do
    match 'lessons' => 'user_lessons#index', :via => :get
    resource :user_lessons, :path => '/lessons'
    match 'lessons/:id' => 'user_lessons#show', :via => :get
    match 'lessons/:id' => 'user_lessons#update', :via => :put
  end

  root to: 'application#index'

  match '/signin', to: 'users#login'
  match '/signout', to: 'users#logout'

end

app/models/lesson.rb
require 'net/http'
require 'json'

class Lesson 
  include Mongoid::Document
  attr_accessible :title, :lesson_id, :default
  field :title,   type: String
  field :default, type: String
  embeds_many :questions
  accepts_nested_attributes_for :questions
#  embeds_many :questions, :class_name => "Question", :inverse_of => :lesson

  def send_on_complete()
    @host = 'localhost'
    @port = '1337'

    @path = ""
    
    qs = Array.new()
    self.questions.each.to_json do |q| qs.push(q) end

    @body = qs

    request = Net::HTTP::Post.new(@path, initheader = {'Content-Type' =>'application/json'})
    request.body = @body
    response = Net::HTTP.new(@host, @port).start {|http| http.request(request) }

  end

  def complete()
    self.completed = true
    send_on_complete()
  end

end

app/models/question.rb
class Question 
  include Mongoid::Document  
  attr_accessible :qText, :correctAnswer, :aText, :id
  before_create :default_values

  field :qText, type: String
  field :correctAnswer, type: String 
  field :aText, type: String
  field :learnerAnswer, type: String
  embedded_in :lesson

  private
    def default_values
      self[:learnerAnswer] ||= "U"
    end
end

app/models/user.rb
class User
  include Mongoid::Document

  attr_accessible :name, :email, :id, :username, :_id
  before_create :default_values

  field :username, type: String #VALIDATE THIS
  field :name, type: String
  field :email, type: String
  field :_id, type: String, default: ->{ username }
  has_one :curr_lesson, :class_name => "UserLesson"
  has_many :lessons, :class_name => "UserLesson"

  private
    def default_values
      UserLesson.get_default.each do |x|
        lessons.push(x)
      end
    end
end

app/models/user_lesson.rb
class UserLesson
  include Mongoid::Document
  field :parent, type: Lesson
  field :completed, type: Boolean 
  embeds_many :questions
  belongs_to :user

  def self.get_default
    default = []
    Lesson.find_by(default: "true") do |lesson|
      default.push(UserLesson.new(parent: lesson))
    end
    #debugger
    return default
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
    @user = session[:user] ? User.find(session[:user]) : User.new
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  protect_from_forgery
  respond_to :html, :json

  def new
    @lesson = Lesson.new
  end

  def index
    @lessons = Lesson.all
    respond_with @lessons
  end

  def show
    @lesson = Lesson.find(params[:id])
    respond_with @lesson
  end

  def update
    @lesson = Lesson.find(params[:id])
    @lesson.update_attributes(params[:lesson] || JSON.parse(params.first.first))
    respond_with @lesson do |lesson|
      lesson.json { render json: @lesson.to_json}
    end
  end

  def create
    @lesson = Lesson.new(params[:lesson] || JSON.parse(params.first.first))
    @lesson.save
    respond_with @lesson
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    respond_with @lesson
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  protect_from_forgery
  respond_to :html, :json

  def index
    @lesson = Lesson.find(params[:lesson_id])
    respond_with @lesson.questions
  end

  def show
    @lesson = Lesson.find(params[:lesson_id])
    @question = @lesson.questions.find(params[:id])
    respond_with @question
  end

  def create
    @lesson = Lesson.find(params[:lesson_id])
    @lesson.questions.create(params[:question] || JSON.parse(params.first.first))
    respond_with @lesson.questions.last
  end

  def edit
    #THIS DONT WORK
  end

  def destroy 
    @lesson = Lesson.find(params[:lesson_id])
    @question = @lesson.questions.find(params[:id])
    @question.destroy
    respond_with @question
  end

  def update
    @lesson = Lesson.find(params[:lesson_id])
    @question = @lesson.questions.find(params[:id])
    @question.update_attributes(params[:question] || JSON.parse(params.first.first))
    respond_with @question do |question|
      question.json { render json: @question.to_json}
    end
  end

#  def new
#    @question = Question.new
#  end
#
#  def edit
#  end
#
#  def show
#  end
#
#  def create
#   @lesson = Lesson.find(params[:question][:lesson_id])
#    @lesson.questions.push(Question.new(aText: params[:question][:qText], qText: params[:question][:aText], correctAnswer: params[:question][:correctAnswer]))
#    # debugger
#    @lesson.save
#    redirect_to edit_lesson_path(@lesson)
#  end

end

app/controllers/user_lessons_controller.rb
class UserLessonsController < ApplicationController
  protect_from_forgery
  respond_to :html, :json

  def index
    @user = User.find(params[:user_id])
    @u_lessons = @user.lessons
    respond_with @u_lessons
  end

  def new
    @u_lesson = UserLesson.new(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @u_lesson = @user.lessons.new(params[:lesson] || JSON.parse(params.first.first))
    @u_lesson.save
    respond_with @u_lesson do |lesson|
      lesson.json { render json: @u_lesson.to_json }
    end
  end

  def show
    @u_lesson = User.find(params[:user_id]).lessons.find(params[:id])
    respond_with @u_lesson
  end

  def destroy
    @u_lesson = User.find(params(:user_id)).find(params(:lesson_id))
    @u_lesson.destroy
    respond_with @u_lesson
  end

  def update
    @u_lesson = UserLesson.find(params[:id])
    @u_lesson.update_attributes(params[:lesson] || JSON.parse(params.first.first))
    respond_with @u_lesson do |lesson|
      lesson.json { render json: @u_lesson.to_json}
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
  respond_to :html, :json

  def index
    @users = User.all
    respond_with @users
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new (params[:user] || JSON.parse(params.first.first))
    @user.save
    session[:user] = @user.id
    respond_with @user
  end

  def show
    @user = User.find(params[:id])
    respond_with @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @user
  end
  
  def update
    @user = User.find(params[:id])
    #HOLY CRAP THIS IS UGLY WHY WONT IT WORK PRETTY
    @user.update_attributes(params[:user] || JSON.parse(params.first.first))
    respond_with @user do |user|
      user.json { render json: @user.to_json }
    end
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user 
      session[:user] = @user.id
      cookies[:user_id] = @user.id
    else
      flash[:error] = "User does not exist"
    end
    redirect_to '/'
  end

  def logout
    session.delete :user
    cookies.delete :user_id
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decider_helper.rb
module DeciderHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn to Program" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
  <div id="main">
    <%= yield %>
  </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/users/_login.html.erb
<%= form_for(:user, url: signin_path) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Sign in", class: "btn btn-primary" %>
<% end %>

app/views/users/_logout.html.erb
<%= button_to "Logout", signout_path %>

app/views/users/_new.html.erb
<h1>Sign up!</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.submit "Create account!" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.submit "Create account!" %>
    <% end %>
  </div>
</div>